export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: "chaat" | "daal-bati" | "pav-bhaji" | "south-indian" | "thali" | "shakes" | "chinese" | "rice-breads"
  tags: ("vegan" | "jain" | "gluten-free" | "chefs-special" | "popular")[]
  isSpicy?: boolean
}

export const menuItems: MenuItem[] = [
  // ============ CHAAT SECTION ============
  {
    id: "samosa",
    name: "Samosa",
    description:
      "Golden-fried pastry pyramids stuffed with spiced potatoes and peas, served with tangy tamarind chutney",
    price: 30,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["vegan", "popular"],
  },
  {
    id: "kachori",
    name: "Kachori",
    description: "Crispy deep-fried bread filled with aromatic moong dal, a Rajasthani delicacy",
    price: 35,
    image: "https://images.unsplash.com/photo-1626132647523-66c7ca2edc63?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["vegan"],
  },
  {
    id: "aloo-tikki",
    name: "Aloo Tikki",
    description: "Crisp potato patties seasoned with aromatic spices, topped with chutneys and yogurt",
    price: 60,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["vegan", "gluten-free"],
  },
  {
    id: "pani-puri",
    name: "Pani Puri",
    description: "Hollow crispy spheres filled with spiced water, tamarind chutney, and potato-chickpea mix",
    price: 50,
    image: "https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["vegan", "popular"],
  },
  {
    id: "sev-puri",
    name: "Sev Puri",
    description: "Crispy puris topped with potatoes, onions, chutneys, and fine sev for the perfect crunch",
    price: 60,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["vegan"],
  },
  {
    id: "dahi-puri",
    name: "Dahi Puri",
    description: "Cool yogurt-filled puris with sweet and tangy chutneys, a refreshing street-food classic",
    price: 70,
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["popular"],
  },
  {
    id: "bhel-puri",
    name: "Bhel Puri",
    description: "Puffed rice tossed with vegetables, chutneys, and sev creating an explosion of textures",
    price: 60,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["vegan"],
  },
  {
    id: "papdi-chaat",
    name: "Papdi Chaat",
    description: "Crispy wafers layered with yogurt, chickpeas, potatoes, and drizzled with tangy chutneys",
    price: 80,
    image: "https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["popular"],
  },
  {
    id: "raj-kachori",
    name: "Raj Kachori",
    description: "The king of chaats - large crispy shell filled with curd, chutneys, sprouts, and sev",
    price: 100,
    image: "https://images.unsplash.com/photo-1626132647523-66c7ca2edc63?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["chefs-special", "popular"],
  },
  {
    id: "samosa-chaat",
    name: "Samosa Chaat",
    description: "Crushed samosa topped with chickpeas, yogurt, and layers of sweet-spicy chutneys",
    price: 90,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop",
    category: "chaat",
    tags: ["popular"],
    isSpicy: true,
  },

  // ============ DAAL BATI & PARATHAS ============
  {
    id: "daal-bati",
    name: "Daal Bati",
    description: "Traditional Rajasthani baked wheat balls served with panchmel dal and pure ghee",
    price: 180,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: ["chefs-special", "popular"],
  },
  {
    id: "daal-bati-churma",
    name: "Daal Bati Churma",
    description: "Complete Rajasthani thali with bati, dal, and sweet churma - a royal feast",
    price: 220,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: ["chefs-special"],
  },
  {
    id: "aloo-paratha",
    name: "Aloo Paratha",
    description: "Whole wheat flatbread stuffed with spiced mashed potatoes, served with butter and curd",
    price: 80,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: ["popular"],
  },
  {
    id: "gobi-paratha",
    name: "Gobi Paratha",
    description: "Flaky paratha stuffed with spiced cauliflower, griddled to golden perfection",
    price: 90,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: [],
  },
  {
    id: "paneer-paratha",
    name: "Paneer Paratha",
    description: "Rich cottage cheese stuffed paratha, a protein-packed vegetarian delight",
    price: 100,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: ["popular"],
  },
  {
    id: "mix-paratha",
    name: "Mix Paratha",
    description: "Multi-vegetable stuffed paratha combining the best of all flavors",
    price: 100,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: [],
  },
  {
    id: "methi-paratha",
    name: "Methi Paratha",
    description: "Fresh fenugreek leaves kneaded into wheat dough, aromatic and nutritious",
    price: 80,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "daal-bati",
    tags: ["jain"],
  },

  // ============ PAV BHAJI SECTION ============
  {
    id: "pav-bhaji",
    name: "Pav Bhaji",
    description: "Mumbai's iconic street food - spiced mashed vegetables served with buttery toasted pav",
    price: 120,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=400&fit=crop",
    category: "pav-bhaji",
    tags: ["popular"],
  },
  {
    id: "cheese-pav-bhaji",
    name: "Cheese Pav Bhaji",
    description: "Classic pav bhaji elevated with generous shavings of melting cheese",
    price: 150,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=400&fit=crop",
    category: "pav-bhaji",
    tags: ["popular"],
  },
  {
    id: "jain-pav-bhaji",
    name: "Jain Pav Bhaji",
    description: "Traditional pav bhaji prepared without onion and garlic, pure and sattvic",
    price: 140,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=400&fit=crop",
    category: "pav-bhaji",
    tags: ["jain"],
  },
  {
    id: "masala-pav",
    name: "Masala Pav",
    description: "Buttery pav rolls stuffed with spiced vegetable filling, a quick Mumbai bite",
    price: 80,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=400&fit=crop",
    category: "pav-bhaji",
    tags: [],
  },
  {
    id: "tawa-pulao",
    name: "Tawa Pulao",
    description: "Aromatic rice stir-fried with pav bhaji masala and mixed vegetables on a hot tawa",
    price: 140,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
    category: "pav-bhaji",
    tags: ["vegan"],
  },

  // ============ SOUTH INDIAN SPECIALS ============
  {
    id: "plain-dosa",
    name: "Plain Dosa",
    description: "Crispy rice and lentil crepe, paper-thin and golden, served with sambar and chutneys",
    price: 80,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eaf59a5?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan", "gluten-free"],
  },
  {
    id: "masala-dosa",
    name: "Masala Dosa",
    description: "Iconic fermented crepe filled with spiced potato masala, a South Indian masterpiece",
    price: 100,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eaf59a5?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan", "popular"],
  },
  {
    id: "mysore-masala-dosa",
    name: "Mysore Masala Dosa",
    description: "Crispy dosa slathered with spicy red chutney, stuffed with fragrant potato filling",
    price: 120,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eaf59a5?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan", "chefs-special"],
    isSpicy: true,
  },
  {
    id: "cheese-dosa",
    name: "Cheese Dosa",
    description: "Crispy dosa generously topped with melted cheese for an indulgent twist",
    price: 130,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eaf59a5?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["popular"],
  },
  {
    id: "rava-dosa",
    name: "Rava Dosa",
    description: "Lacy semolina crepe with crispy edges and soft center, instant and delicious",
    price: 100,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eaf59a5?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: [],
  },
  {
    id: "onion-rava-dosa",
    name: "Onion Rava Dosa",
    description: "Semolina dosa studded with caramelized onions for extra flavor and crunch",
    price: 110,
    image: "https://images.unsplash.com/photo-1668236543090-82eb5eaf59a5?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: [],
  },
  {
    id: "idli",
    name: "Idli (2 Pcs)",
    description: "Steamed rice cakes, soft as clouds, served with coconut chutney and sambar",
    price: 60,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan", "gluten-free", "jain"],
  },
  {
    id: "medu-vada",
    name: "Medu Vada (2 Pcs)",
    description: "Crispy golden doughnuts made from urad dal, crunchy outside and fluffy inside",
    price: 70,
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan", "gluten-free"],
  },
  {
    id: "idli-vada-combo",
    name: "Idli Vada Combo",
    description: "Best of both worlds - soft idli paired with crispy vada, sambar and chutneys",
    price: 100,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["popular"],
  },
  {
    id: "uttapam",
    name: "Uttapam",
    description: "Thick rice pancake topped with onions, tomatoes, and chilies, griddled to perfection",
    price: 90,
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan"],
  },
  {
    id: "onion-uttapam",
    name: "Onion Uttapam",
    description: "Savory rice pancake loaded with crispy caramelized onions",
    price: 100,
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: [],
  },
  {
    id: "upma",
    name: "Upma",
    description: "Tempered semolina porridge with mustard seeds, curry leaves, and vegetables",
    price: 70,
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["vegan"],
  },
  {
    id: "pongal",
    name: "Pongal",
    description: "Comforting rice and moong dal dish tempered with black pepper, cumin, and ghee",
    price: 90,
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&h=400&fit=crop",
    category: "south-indian",
    tags: ["gluten-free"],
  },

  // ============ THALI SECTION ============
  {
    id: "south-indian-thali",
    name: "South Indian Thali",
    description: "Complete South Indian meal with rice, sambar, rasam, kootu, poriyal, curd, and dessert",
    price: 200,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    category: "thali",
    tags: ["popular"],
  },
  {
    id: "north-indian-thali",
    name: "North Indian Thali",
    description: "Royal spread with dal, paneer, sabzi, roti, rice, raita, pickle, and sweet",
    price: 220,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    category: "thali",
    tags: ["popular"],
  },
  {
    id: "gujarati-thali",
    name: "Gujarati Thali",
    description: "Sweet and savory Gujarati delicacies - dal, kadhi, sabzi, rotla, rice, and more",
    price: 200,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    category: "thali",
    tags: [],
  },
  {
    id: "rajasthani-thali",
    name: "Rajasthani Thali",
    description: "Royal Rajasthani feast with dal bati, gatte ki sabzi, ker sangri, and churma",
    price: 250,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    category: "thali",
    tags: ["chefs-special"],
  },
  {
    id: "special-thali",
    name: "Special Thali",
    description: "Chef's curated selection of the day's best dishes - a complete dining experience",
    price: 280,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    category: "thali",
    tags: ["chefs-special", "popular"],
  },
  {
    id: "mini-thali",
    name: "Mini Thali",
    description: "Smaller portion thali perfect for light appetites - dal, sabzi, roti, rice",
    price: 150,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
    category: "thali",
    tags: [],
  },

  // ============ SHAKES & BEVERAGES ============
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    description: "Creamy yogurt blended with Alphonso mango pulp, a refreshing tropical delight",
    price: 80,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&h=400&fit=crop",
    category: "shakes",
    tags: ["popular"],
  },
  {
    id: "sweet-lassi",
    name: "Sweet Lassi",
    description: "Traditional Punjabi yogurt drink, thick and creamy with a hint of cardamom",
    price: 60,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&h=400&fit=crop",
    category: "shakes",
    tags: [],
  },
  {
    id: "salted-lassi",
    name: "Salted Lassi",
    description: "Refreshing savory lassi with a pinch of roasted cumin and salt",
    price: 50,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&h=400&fit=crop",
    category: "shakes",
    tags: ["jain"],
  },
  {
    id: "buttermilk",
    name: "Chaas (Buttermilk)",
    description: "Spiced buttermilk with cumin, mint, and coriander - perfect digestive",
    price: 40,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&h=400&fit=crop",
    category: "shakes",
    tags: ["jain", "gluten-free"],
  },
  {
    id: "cold-coffee",
    name: "Cold Coffee",
    description: "Chilled creamy coffee blended with ice cream for a sweet caffeine kick",
    price: 90,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=400&fit=crop",
    category: "shakes",
    tags: ["popular"],
  },
  {
    id: "chocolate-shake",
    name: "Chocolate Shake",
    description: "Rich and indulgent chocolate milkshake topped with whipped cream",
    price: 100,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&h=400&fit=crop",
    category: "shakes",
    tags: [],
  },
  {
    id: "vanilla-shake",
    name: "Vanilla Shake",
    description: "Classic vanilla milkshake, creamy and smooth with real vanilla",
    price: 90,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&h=400&fit=crop",
    category: "shakes",
    tags: [],
  },
  {
    id: "strawberry-shake",
    name: "Strawberry Shake",
    description: "Fresh strawberry milkshake, pink, fruity, and absolutely delicious",
    price: 100,
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600&h=400&fit=crop",
    category: "shakes",
    tags: [],
  },
  {
    id: "fresh-lime-soda",
    name: "Fresh Lime Soda",
    description: "Zesty lime juice with soda, available sweet or salted to your preference",
    price: 50,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&h=400&fit=crop",
    category: "shakes",
    tags: ["vegan"],
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    description: "Aromatic spiced tea brewed with ginger, cardamom, and cinnamon",
    price: 30,
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&h=400&fit=crop",
    category: "shakes",
    tags: ["popular"],
  },

  // ============ CHINESE SECTION ============
  {
    id: "veg-manchurian-dry",
    name: "Veg Manchurian Dry",
    description: "Crispy vegetable balls tossed in spicy Indo-Chinese sauce with bell peppers",
    price: 140,
    image: "https://images.unsplash.com/photo-1569058242567-93de6f36f8e6?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["popular"],
    isSpicy: true,
  },
  {
    id: "veg-manchurian-gravy",
    name: "Veg Manchurian Gravy",
    description: "Vegetable balls swimming in rich, tangy brown sauce - comfort in a bowl",
    price: 160,
    image: "https://images.unsplash.com/photo-1569058242567-93de6f36f8e6?w=600&h=400&fit=crop",
    category: "chinese",
    tags: [],
    isSpicy: true,
  },
  {
    id: "chilli-paneer-dry",
    name: "Chilli Paneer Dry",
    description: "Crispy paneer cubes wok-tossed with peppers, onions, and fiery sauces",
    price: 180,
    image: "https://images.unsplash.com/photo-1569058242567-93de6f36f8e6?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["popular"],
    isSpicy: true,
  },
  {
    id: "chilli-paneer-gravy",
    name: "Chilli Paneer Gravy",
    description: "Cottage cheese in spicy Indo-Chinese gravy, perfect with fried rice",
    price: 200,
    image: "https://images.unsplash.com/photo-1569058242567-93de6f36f8e6?w=600&h=400&fit=crop",
    category: "chinese",
    tags: [],
    isSpicy: true,
  },
  {
    id: "veg-fried-rice",
    name: "Veg Fried Rice",
    description: "Wok-tossed rice with crisp vegetables, soy sauce, and aromatic seasonings",
    price: 120,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["vegan"],
  },
  {
    id: "schezwan-fried-rice",
    name: "Schezwan Fried Rice",
    description: "Fiery fried rice with Schezwan sauce, vegetables, and bold spices",
    price: 140,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["popular"],
    isSpicy: true,
  },
  {
    id: "veg-hakka-noodles",
    name: "Veg Hakka Noodles",
    description: "Silky noodles stir-fried with colorful vegetables and soy sauce",
    price: 120,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["vegan"],
  },
  {
    id: "schezwan-noodles",
    name: "Schezwan Noodles",
    description: "Spicy noodles coated in fiery Schezwan sauce with crisp vegetables",
    price: 140,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop",
    category: "chinese",
    tags: [],
    isSpicy: true,
  },
  {
    id: "manchow-soup",
    name: "Manchow Soup",
    description: "Thick vegetable soup topped with crispy noodles - a warming starter",
    price: 80,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["popular"],
  },
  {
    id: "hot-and-sour-soup",
    name: "Hot & Sour Soup",
    description: "Tangy and spicy soup with vegetables, tofu, and a kick of white pepper",
    price: 80,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["vegan"],
    isSpicy: true,
  },
  {
    id: "spring-roll",
    name: "Spring Roll (4 Pcs)",
    description: "Crispy golden rolls stuffed with spiced cabbage and vegetables",
    price: 100,
    image: "https://images.unsplash.com/photo-1548507200-e9e3f5e593ad?w=600&h=400&fit=crop",
    category: "chinese",
    tags: ["vegan"],
  },

  // ============ RICE & BREADS ============
  {
    id: "jeera-rice",
    name: "Jeera Rice",
    description: "Fragrant basmati rice tempered with cumin seeds and pure ghee",
    price: 100,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["vegan", "gluten-free", "jain"],
  },
  {
    id: "plain-rice",
    name: "Plain Rice",
    description: "Steamed long-grain basmati rice, fluffy and perfectly cooked",
    price: 80,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["vegan", "gluten-free", "jain"],
  },
  {
    id: "veg-pulao",
    name: "Veg Pulao",
    description: "Aromatic rice cooked with mixed vegetables and whole spices",
    price: 140,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: [],
  },
  {
    id: "veg-biryani",
    name: "Veg Biryani",
    description: "Layered Hyderabadi biryani with vegetables, saffron, and aromatic spices",
    price: 180,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["chefs-special", "popular"],
  },
  {
    id: "paneer-biryani",
    name: "Paneer Biryani",
    description: "Rich biryani loaded with cottage cheese cubes and dum-cooked spices",
    price: 200,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["popular"],
  },
  {
    id: "plain-roti",
    name: "Plain Roti",
    description: "Whole wheat flatbread, soft and fresh from the tawa",
    price: 20,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["vegan", "jain"],
  },
  {
    id: "butter-roti",
    name: "Butter Roti",
    description: "Soft roti brushed generously with golden butter",
    price: 30,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["jain"],
  },
  {
    id: "plain-naan",
    name: "Plain Naan",
    description: "Leavened bread baked in tandoor, soft and pillowy",
    price: 40,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: [],
  },
  {
    id: "butter-naan",
    name: "Butter Naan",
    description: "Tandoori naan brushed with melted butter, rich and indulgent",
    price: 50,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["popular"],
  },
  {
    id: "garlic-naan",
    name: "Garlic Naan",
    description: "Aromatic naan loaded with minced garlic and fresh coriander",
    price: 60,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["popular"],
  },
  {
    id: "laccha-paratha",
    name: "Laccha Paratha",
    description: "Multi-layered flaky paratha, each layer crispy and buttery",
    price: 50,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: [],
  },
  {
    id: "missi-roti",
    name: "Missi Roti",
    description: "Spiced gram flour roti, a Rajasthani specialty with robust flavors",
    price: 40,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
    category: "rice-breads",
    tags: ["vegan"],
  },
]

export const categories = [
  { id: "chaat", label: "Chaat Corner", icon: "🥟" },
  { id: "daal-bati", label: "Daal Bati & Parathas", icon: "🫓" },
  { id: "pav-bhaji", label: "Pav Bhaji", icon: "🍞" },
  { id: "south-indian", label: "South Indian", icon: "🍃" },
  { id: "thali", label: "Thali", icon: "🍽️" },
  { id: "shakes", label: "Shakes & Beverages", icon: "🥤" },
  { id: "chinese", label: "Chinese", icon: "🥢" },
  { id: "rice-breads", label: "Rice & Breads", icon: "🍚" },
] as const

export type CategoryId = (typeof categories)[number]["id"]
